### ISSUE TITLE
Guesses and keyboard not matching

### ISSUE THREAD

**Issue by jackos-1** [MulesGaming/minecraft-wordle#40] opened 2024-06-09 05:45 UTC
I was playing and in the boxes where your guesses are the letter T was yellow but in the keyboard below it was grey. I felt that this might confuse people if they have the same bug.

**Comment by MulesGaming** [comment] 2024-06-11 02:50
This isn't suppose to happen. What was your word?

**Comment by RDRapidHyperion** [comment] 2024-06-27 19:20
I had encountered a similar issue here with the letter E. Here, the word ended up being apple. Though maybe here it may have been caused by entering a word with the letter E twice? 
![image](https://github.com/MulesGaming/minecraft-wordle/assets/77507343/110d8ec1-3883-4bdb-ab00-5765e5e633cd)
When I entered another word with a single E, it fixed itself.
![image](https://github.com/MulesGaming/minecraft-wordle/assets/77507343/fbbdd927-2913-4998-a977-8166938da318)

**Comment by MulesGaming** [comment] 2024-06-27 22:24
Should be fixed now!

**Closed by MulesGaming** 2024-06-27 22:24 UTC
