### ISSUE TITLE
"agian" should be "again"

### ISSUE THREAD

**Issue by Albertamere** [MulesGaming/minecraft-wordle#23] opened 2023-12-28 14:44 UTC
![image](https://github.com/MulesGaming/minecraft-wordle/assets/71387711/26833802-9504-423e-8941-964a4e083fc5)

in the prompt about today's word, the link to play again has a typo

**Comment by MulesGaming** [comment] 2023-12-28 16:36
Duplicate of #1

**Closed by MulesGaming** 2023-12-28 16:36 UTC
Labels: duplicate
