### ISSUE TITLE
Streak doesn't reset when you lose

### ISSUE THREAD

**Issue by DhruvMitna** [MulesGaming/minecraft-wordle#20] opened 2023-12-28 09:34 UTC
The winstreak does not reset if you lose and only resets at the next game instead.

Initial streak:

![Screenshot_20231228_145931_Iceraven.png](https://github.com/MulesGaming/minecraft-wordle/assets/75002001/3ad9ebeb-498a-42c4-9ad1-71dd55c4bb9d)

After losing once, the streak does not reset to 0:

![Screenshot_20231228_150133_Iceraven.png](https://github.com/MulesGaming/minecraft-wordle/assets/75002001/bb983465-cdda-4a50-950a-cb388ec6e965)

It gets reset and updated after the second game.

**Comment by MulesGaming** [comment] 2023-12-29 04:19
This was caused by two functions in the wrong order. Should be fixed now, Thanks.

**Closed by MulesGaming** 2023-12-29 04:19 UTC
Labels: bug
